# Assignment 1 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [85]:
# required imports
import numpy as np
import fnmatch


Suppose we have 3 files containing data :

### File Contents

<img src="1.png"/>
<img src="2.png"/>
<img src="3.png"/>

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [86]:
# Here we have intialized some variables, you can add more if required.
file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set

In [87]:
#Your code starts here   
from pathlib import Path 
directory = "."
files = Path(directory).glob('*.txt')
i =0;
for file in files:
    files_dict[i] = file.name
    file_count += 1
    i += 1
#Your code ends here       

Displaying the count of files.

In [88]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 3


Displaying Dictionary containing all files.

In [89]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {0: 'f1.txt', 1: 'f2.txt', 2: 'f3.txt'}


# Step 3 Extract Unique Vocabulary

In [90]:
# write code to print all the unique words in every file and store them in a set

In [100]:
#Your code starts here
non_unique_words = []
for file in files_dict:
    with open(files_dict[file],"r") as file:
        for line in file:
            for word in line.split():
                non_unique_words.append(word.lower())
                unique_word_set.add(word.lower())
print(unique_word_set)
#Your code ends here

{'this', 'book', 'is', 'pen', 'interesting', 'my'}


### Expected Output

<img src="4.png"/>

# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

In [92]:
# Create Term doc matrix such that colmns will be unique words and all the files will be rows
# Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [101]:
#Your code starts here
TermDocMatrix = np.zeros((file_count,len(unique_word_set)))
unique_word_dict = {}
def getappearancecount(a):
    appearance_count = 0
    for word in non_unique_words:
        if(a == word):
            appearance_count +=1
    return appearance_count
temp =0
for word in unique_word_set:
    temp = getappearancecount(word)
    unique_word_dict[word] = temp
print("Dictionary of Unique Words With Appearance Count :\n")
print(unique_word_dict)
print("\nDictionary of Files: \n")
print(files_dict)
#Your code ends here

Dictionary of Unique Words With Appearance Count :

{'this': 2, 'book': 2, 'is': 3, 'pen': 1, 'interesting': 1, 'my': 3}

Dictionary of Files: 

{0: 'f1.txt', 1: 'f2.txt', 2: 'f3.txt'}


### Expected Output

<img src="5.png"/>

# Step 5 Fill Term Document Matrix

In [75]:
# Fill the term doc matrix by checking if the unique word exists in a file or not
# If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
# Do the same for all the files present in the directory

In [99]:
#Your code starts here 
r = 0
def isExist(a,f):
    with open(f,"r") as file:
        for line in file:
            for word in line.split():
                if(a == word):
                    return True
    return False
for file in files_dict:
    c = 0
    for word in unique_word_set:
        if(isExist(word,files_dict[file])):
            TermDocMatrix[r][c] = 1
        c += 1
    r += 1
print("TERM DOC MATRIX After Filling :\n")
print(TermDocMatrix)
#Your code ends here

TERM DOC MATRIX After Filling :

[[0. 1. 1. 0. 0. 1.]
 [0. 0. 1. 1. 0. 1.]
 [0. 1. 1. 0. 1. 0.]]


### Expected Output

<img src="6.png"/>

# Step 6 Ask for a user Query

In [77]:
# For user query make a column vector of length of all the unique words present in a set

In [78]:
#Your code starts here    
v = np.zeros((len(unique_word_set),1))
print(v)
#Your code ends here

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

<img src="7.png"/>

In [79]:
query = input("\nWrite something for searching  ")
# Check every word of query if it exists in the set of unique words or not
# If exixts then increment the count of that word in word dictionary
tt = query.split()
for t in tt:
    row = 0
    for word in unique_word_set:
        if(t == word):
            v[row][0] = v[row][0] + 1
        row += 1


Write something for searching  This book is Good


### Expected Output

<img src="8.png"/>

# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [80]:
#Your code starts here  
print(v)
largest = v[0][0]
max_index = 0
for i in range(len(v)):
    if(v[i][0] > largest):
        largest = v[i][0]
        max_index = i
print("Maximum in Resultant is ", largest)
print("\n Index of maximum in resultant is ", max_index)
#Your code ends here

[[1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]]
Maximum in Resultant is  1.0

 Index of maximum in resultant is  0


### Expected Output

<img src="9.png"/>

# Step 8 Display the contents of file


In [81]:
#Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [82]:
#Your code starts here
itr = 0
max_val_word = ""
for val in unique_word_set:
    if(itr == max_index):
        max_value_word = val
        break
    itr += 1
#print(max_value_word)

max_value_word_Arr = []
for file in files_dict:
    with open(files_dict[file],"r") as f:
        count = 0
        for line in f:
            for word in line.split():
                if(word == max_value_word):
                    count += 1
        max_value_word_Arr.append(count)
m_index = 0
m_value = max_value_word_Arr[0]
for j in range(len(max_value_word_Arr)):
    if(max_value_word_Arr[j] > m_value):
        m_value = max_value_word_Arr[j]
        m_index = j
max_value_filename = files_dict[m_index]
print(max_value_filename)
with open(max_value_filename,"r") as max_val_f:
    for line in max_val_f:
        print(line)
#Your code ends here

f1.txt
This is my book


Congratulations Now you are able to build your own small IRS.